baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = ["docsy"]
publishDir = "/docs"


[module]
[module.hugoVersion]
extended = true
min = "0.100.2"
max = "0.100.2"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"


