baseURL = 'https://paulscott-ia.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"


theme = "docsy"